"""
Django settings for apps.akd_studio project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta
from dotenv import load_dotenv
from pathlib import Path

# Load env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Define MEDIA_ROOT
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.getenv('DEBUG_MODE')))

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(', ')

# Application definition
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'apps.akd_studio',
	'apps.authentication',
	'rest_framework',
	'rest_framework_simplejwt',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'apps.akd_studio.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'apps.akd_studio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE'  : os.getenv('DB_ENGINE'),
		'NAME'	  : os.getenv('DB_NAME'),
		'USER'	  : os.getenv('DB_USER'),
		'PASSWORD': os.getenv('DB_PASS'),
		'HOST'	  : os.getenv('DB_HOST'),
		'PORT'	  : os.getenv('DB_PORT')
	}
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTHENTICATION_CLASSES
REST_FRAMEWORK = {
	'DEFAULT_AUTHENTICATION_CLASSES': [
		'rest_framework_simplejwt.authentication.JWTAuthentication',
	],
	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.IsAuthenticated',
	]
}

# SIMPLE_JWT - https://django-rest-framework-simplejwt.readthedocs.io/en/latest/getting_started.html
SIMPLE_JWT = {
	'ACCESS_TOKEN_LIFETIME'	: timedelta(hours=int(os.getenv('ACCESS_TOKEN_LIFETIME_HOURS'))),
	'REFRESH_TOKEN_LIFETIME': timedelta(hours=int(os.getenv('REFRESH_TOKEN_LIFETIME_HOURS'))),
	'UPDATE_LAST_LOGIN'		: True,
	
	'ALGORITHM'	 : 'HS256',
	'SIGNING_KEY': SECRET_KEY,
	'JTI_CLAIM'	 : 'jti',

	'AUTH_HEADER_TYPES': ('Bearer',),
	'AUTH_HEADER_NAME' : 'HTTP_AUTHORIZATION',
	'USER_ID_FIELD'	   : 'id',
	'USER_ID_CLAIM'	   : 'user_id',
	
	'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
	'TOKEN_TYPE_CLAIM'	: 'token_type',
	'TOKEN_USER_CLASS'	: 'rest_framework_simplejwt.models.TokenUser',

	'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
	'TOKEN_OBTAIN_SERIALIZER' : 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
	'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
}

# MASTER REGEX
MASTER_REGEX = {
	'name': {
		'regex': r'^[A-Za-z]{2,}$',
		'desc' : 'Names must be minimum 2 characters long and contain only letters.'
	},
	'usnm': {
		'regex': r'^[a-zA-Z0-9._]{2,}$',
		'desc' : 'Username must be minimum 2 characters long and can contain letters, numbers, underscores, and periods.'
	},
	'emal': {
		'regex': r'^[a-zA-Z0-9_.+-]{2,}+@[a-zA-Z0-9-]{2,}+\.[a-zA-Z]{2,}$',
		'desc' : 'Email must be a valid email address format.'
	},
	'pswd': {
		'regex': r'^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$',
		'desc' : 'Password must be minimum 8 characters long, include at least one lowercase letter, one uppercase letter, one number, and one special character.'
	},
}
